{% set name = "httpcore" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d59d3d437405f14253d9a5889026e1e8657b057399274f8769a08a95084351a1

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - h11 >=0.11,<0.13
    - h2 >=3,<5
    - sniffio ==1.*
    - anyio ==3.*

test:
  imports:
    - httpcore

about:
  home: https://github.com/encode/httpcore
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The next generation HTTP client.

extra:
  recipe-maintainers:
    - nicoddemus
